/**
 * HIGH-END CRAFTSMANSHIP BRAND family
 * Rich dark charcoal bg, Cormorant Garamond + Montserrat, asymmetric visual-led layout.
 * Think luxury architectural firm / high-end contractor portfolio.
 */
const { escHtml } = require('../shared/utils');
const { getCopy } = require('../shared/copy');
const { generateWidget } = require('../shared/widget');
const { getTheme } = require('../shared/niche-themes');

const designProfile = {
  layout: 'asymmetric-portfolio-studio',
  hero: 'full-bleed-image-with-overlay-card',
  typography: 'cormorant-garamond+montserrat',
  sectionOrder: 'transparent-nav|hero-overlap|philosophy|project-showcase|services-editorial|pullquote|process|studio-brief|footer',
  components: 'project-tiles|editorial-service-rows|single-pullquote|process-columns|studio-brief-form',
  personality: 'artisanal-detail-obsessed-premium',
  ctaStrategy: 'portfolio-first-consultation',
  colorScheme: 'niche-themed-dark-warm-stone',
  density: 'dramatic-asymmetric',
  navStyle: 'transparent-overlay-minimal',
};

module.exports = {
  name: 'craft',
  label: 'High-End Craftsmanship',
  designProfile,

  generate(lead, niche) {
    const c = getCopy('craft', niche, lead);
    const t = getTheme('craft', niche);
    const tc = t.colors;
    const biz = escHtml(lead.business_name);
    const city = escHtml(lead.city || 'Your City');
    const state = escHtml(lead.state || '');
    const phone = escHtml(lead.phone || '(555) 000-0000');
    const phoneHref = (lead.phone || '5550000000').replace(/[^0-9+]/g, '');
    const cityState = [lead.city, lead.state].filter(Boolean).join(', ');
    const heroImg = t.heroImages.primary;
    const projImg1 = t.heroImages.project1;
    const projImg2 = t.heroImages.project2;
    const badges = t.badges;
    const icons = t.icons;
    const sectionPattern = t.pattern(tc.accent, 0.025);

    const widget = generateWidget(lead, {
      emoji: c.emoji,
      headBg: `linear-gradient(135deg,${tc.primary},${tc.bgAlt})`,
      avatarBg: tc.bgAlt,
      fabBg: tc.primary,
      fabRadius: '12px',
      fabSize: '50px',
      panelRadius: '12px',
      bodyFont: "'Montserrat',sans-serif",
      headingFont: "'Cormorant Garamond',serif",
      userMsgBg: tc.accent,
      sendBg: tc.accent,
      sendHoverBg: tc.accentHover,
      linkColor: tc.accent,
      inputFocusBorder: tc.accent,
      inputFocusRing: tc.accentLight,
      qrBorder: tc.border,
      qrColor: tc.accent,
      qrBg: tc.accentLight,
      qrHoverBg: tc.accent,
      qrRadius: '6px',
      inputRadius: '8px',
      msgBotRadius: '2px 12px 12px 12px',
      msgUserRadius: '12px 12px 2px 12px',
      chatBg: '#F9F7F4',
      fabShadow: '0 4px 20px rgba(0,0,0,.3)',
    }, c.quickReplies, c.serviceOptions);

    // Services as editorial list with niche icons (NOT card grid — this is key differentiation)
    const serviceList = c.services.map((svc, i) => `
          <div class="service-row flex flex-col md:flex-row md:items-baseline gap-2 md:gap-8 py-6 ${i < c.services.length - 1 ? 'border-b border-white/[.06]' : ''} reveal">
            <div class="md:w-72 flex-shrink-0 flex items-center gap-3">
              <span class="w-7 h-7 flex-shrink-0" style="color:${tc.accent};">${icons[i % icons.length]}</span>
              <h3 class="font-serif text-xl md:text-2xl font-semibold" style="letter-spacing:-0.01em;color:${tc.textLight};">${escHtml(svc.title)}</h3>
            </div>
            <p class="text-sm leading-relaxed flex-1" style="color:${tc.textMuted};">${escHtml(svc.desc)}</p>
          </div>`).join('\n');

    // Single large pull-quote (NOT a grid of testimonials)
    const mainTestimonial = c.testimonials[0];

    const serviceOpts = c.serviceOptions.map(o => `              <option>${escHtml(o)}</option>`).join('\n');

    // Niche-specific badge markup
    const badgeHtml = badges.map(b =>
      `<span class="border px-3 py-1.5 rounded-full" style="border-color:${tc.border};">${escHtml(b)}</span>`
    ).join('\n          ');

    return `<!-- DEMO: ${biz} | Family: craft | Generated by Variation Engine -->
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta name="robots" content="noindex, nofollow">
<title>${biz} — ${c.nicheLabel} | ${escHtml(cityState)}</title>
<link rel="preconnect" href="https://fonts.googleapis.com">
<link href="https://fonts.googleapis.com/css2?family=Cormorant+Garamond:ital,wght@0,400;0,500;0,600;0,700;1,400;1,500&family=Montserrat:wght@300;400;500;600;700&display=swap" rel="stylesheet">
<script src="https://cdn.tailwindcss.com"></script>
<script>
tailwind.config={theme:{extend:{colors:{charcoal:'${tc.primary}','charcoal-light':'${tc.bgAlt}',warm:'${tc.textLight}',gold:'${tc.accent}','gold-light':'${tc.accentHover}'},fontFamily:{serif:['Cormorant Garamond','Georgia','serif'],sans:['Montserrat','sans-serif']}}}}
</script>
<style>
body{font-family:'Montserrat',sans-serif;background:${tc.bg};color:${tc.textLight};-webkit-font-smoothing:antialiased;}
h1,h2,h3{font-family:'Cormorant Garamond',Georgia,serif;}
.reveal{opacity:0;transform:translateY(16px);transition:opacity .6s cubic-bezier(.25,.46,.45,.94),transform .6s cubic-bezier(.25,.46,.45,.94);}
.reveal.active{opacity:1;transform:translateY(0);}
.nav-solid{background:rgba(26,26,26,.97);backdrop-filter:blur(12px);-webkit-backdrop-filter:blur(12px);border-bottom:1px solid rgba(255,255,255,.04);}
.niche-pattern{background-image:${sectionPattern};background-repeat:repeat;}
</style>
</head>
<body>

<!-- NAV — transparent overlay, solid on scroll -->
<nav id="navbar" class="fixed top-0 left-0 right-0 z-40 transition-all duration-300">
  <div class="max-w-7xl mx-auto px-6 lg:px-10">
    <div class="flex items-center justify-between h-20">
      <a href="#" class="font-serif text-2xl font-semibold tracking-tight" style="color:${tc.textLight};">${biz}</a>
      <div class="hidden lg:flex items-center gap-10">
        <a href="#work" class="hover:text-warm text-xs font-medium uppercase tracking-[0.15em] transition-colors" style="color:${tc.textMuted};">Our Work</a>
        <a href="#services" class="hover:text-warm text-xs font-medium uppercase tracking-[0.15em] transition-colors" style="color:${tc.textMuted};">Services</a>
        <a href="#process" class="hover:text-warm text-xs font-medium uppercase tracking-[0.15em] transition-colors" style="color:${tc.textMuted};">Process</a>
        <a href="#contact" class="hover:text-warm text-xs font-medium uppercase tracking-[0.15em] transition-colors" style="color:${tc.textMuted};">Contact</a>
      </div>
      <div class="hidden lg:flex items-center gap-6">
        <a href="tel:${phoneHref}" class="text-xs font-semibold uppercase tracking-[0.12em] transition-colors" style="color:${tc.textLight};">Call ${phone}</a>
        <a href="#contact" class="inline-flex text-xs font-medium uppercase tracking-[0.12em] pb-0.5 transition-colors" style="color:${tc.accent};border-bottom:1px solid ${tc.border};">
          ${escHtml(c.cta1)} →
        </a>
      </div>
      <button id="mobile-toggle" class="lg:hidden p-2" style="color:${tc.textLight};" aria-label="Menu">
        <svg class="w-6 h-6" fill="none" stroke="currentColor" stroke-width="1.5" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" d="M4 6h16M4 12h16M4 18h16"/></svg>
      </button>
    </div>
  </div>
  <div id="mobile-menu" class="hidden lg:hidden border-t border-white/[.04]" style="background:${tc.primary};">
    <div class="px-6 py-6 space-y-4">
      <a href="#work" class="mobile-link block text-sm font-medium" style="color:${tc.textMuted};">Our Work</a>
      <a href="#services" class="mobile-link block text-sm font-medium" style="color:${tc.textMuted};">Services</a>
      <a href="#process" class="mobile-link block text-sm font-medium" style="color:${tc.textMuted};">Process</a>
      <a href="tel:${phoneHref}" class="mobile-link block text-sm font-semibold" style="color:${tc.textLight};">Call ${phone}</a>
      <a href="#contact" class="mobile-link block text-sm font-medium" style="color:${tc.accent};">${escHtml(c.cta1)} →</a>
    </div>
  </div>
</nav>

<!-- HERO — large image with overlapping text card -->
<section class="relative" style="min-height:90vh;">
  <div class="relative w-full" style="height:90vh;">
    <img src="${escHtml(heroImg)}" alt="${escHtml(c.nicheLabel)}" class="w-full h-full object-cover" style="filter:brightness(0.5) saturate(0.7);">
    <!-- Overlapping card — positioned bottom-left -->
    <div class="absolute bottom-0 left-0 md:bottom-12 md:left-10 lg:left-16 w-full md:w-auto md:max-w-xl z-10">
      <div class="backdrop-blur-md p-8 md:p-12 md:rounded-xl" style="background:rgba(26,26,26,.95);border:1px solid rgba(255,255,255,.05);">
        <p class="text-xs font-medium uppercase tracking-[0.2em] mb-4" style="color:${tc.accent};">${escHtml(c.nicheLabel)} · ${city}</p>
        <h1 class="font-serif font-semibold mb-4" style="color:${tc.textLight};font-size:clamp(2rem,4vw,3.2rem);line-height:1.1;letter-spacing:-0.02em;">
          ${escHtml(c.headline)}
        </h1>
        <p class="text-sm leading-relaxed mb-6 max-w-md" style="color:${tc.textMuted};">${escHtml(c.subline)}</p>
        <div class="flex flex-wrap items-center gap-4">
          <a href="#contact" class="text-xs font-semibold uppercase tracking-[0.12em] pb-0.5 transition-colors" style="color:${tc.accent};border-bottom:1px solid ${tc.accent};">
            ${escHtml(c.cta1)} →
          </a>
          <a href="tel:${phoneHref}" class="text-xs font-semibold uppercase tracking-[0.12em] transition-colors" style="color:${tc.textLight};">
            Call ${phone}
          </a>
          <a href="#work" class="text-xs font-medium uppercase tracking-[0.12em] transition-colors" style="color:${tc.textMuted};">
            ${escHtml(c.cta2)}
          </a>
        </div>
        <div class="flex flex-wrap items-center gap-2 mt-5 text-[11px] uppercase tracking-[0.14em]" style="color:${tc.textMuted};">
          ${badgeHtml}
        </div>
        <div class="flex items-center gap-4 mt-6 pt-5 border-t border-white/[.06] text-xs" style="color:${tc.textMuted};">
          <span>${escHtml(c.stats.years)} years</span>
          <span class="w-px h-3 bg-white/[.08]"></span>
          <span>${escHtml(c.stats.jobs)}+ projects</span>
          <span class="w-px h-3 bg-white/[.08]"></span>
          <span class="inline-flex items-center gap-1">${escHtml(c.stats.rating)}<svg class="w-3.5 h-3.5" style="color:${tc.accent}" fill="currentColor" viewBox="0 0 20 20"><path d="M9.049 2.927c.3-.921 1.603-.921 1.902 0l1.07 3.292a1 1 0 00.95.69h3.462c.969 0 1.371 1.24.588 1.81l-2.8 2.034a1 1 0 00-.364 1.118l1.07 3.292c.3.921-.755 1.688-1.54 1.118l-2.8-2.034a1 1 0 00-1.175 0l-2.8 2.034c-.784.57-1.838-.197-1.539-1.118l1.07-3.292a1 1 0 00-.364-1.118L2.98 8.72c-.783-.57-.38-1.81.588-1.81h3.461a1 1 0 00.951-.69l1.07-3.292z"/></svg></span>
        </div>
      </div>
    </div>
  </div>
</section>

<!-- PHILOSOPHY -->
<section class="py-24 md:py-32 niche-pattern">
  <div class="max-w-3xl mx-auto px-6 lg:px-10 text-center reveal">
    <p class="text-xs font-medium uppercase tracking-[0.2em] mb-6" style="color:${tc.accent};">Our Philosophy</p>
    <h2 class="font-serif font-semibold mb-6" style="color:${tc.textLight};font-size:clamp(1.6rem,3vw,2.4rem);line-height:1.2;letter-spacing:-0.02em;">
      ${escHtml(c.whyTitle)}
    </h2>
    <p class="leading-relaxed text-sm md:text-base max-w-xl mx-auto" style="color:${tc.textMuted};">${escHtml(c.whySub)} Every detail matters. From the materials we select to the techniques we use, we bring decades of trade mastery to every project. The difference shows — in the work, and in the result.</p>
  </div>
</section>

<!-- PROJECT SHOWCASE — visual cards -->
<section id="work" class="pb-24 md:pb-32">
  <div class="max-w-6xl mx-auto px-6 lg:px-10">
    <div class="flex items-end justify-between mb-12 reveal">
      <div>
        <p class="text-xs font-medium uppercase tracking-[0.2em] mb-3" style="color:${tc.accent};">Recent Projects</p>
        <h2 class="font-serif text-3xl md:text-4xl font-semibold" style="color:${tc.textLight};letter-spacing:-0.02em;">Our Work</h2>
      </div>
    </div>
    <div class="grid grid-cols-1 md:grid-cols-2 gap-5 reveal">
      <div class="group relative overflow-hidden rounded-lg cursor-pointer" style="aspect-ratio:4/3;">
        <img src="${escHtml(projImg1)}" alt="Recent project" class="w-full h-full object-cover transition-transform duration-500 group-hover:scale-105" style="filter:brightness(0.6);">
        <div class="absolute inset-0 flex flex-col justify-end p-8">
          <p class="text-xs uppercase tracking-[0.15em] mb-2" style="color:${tc.accent};">${city} Residential</p>
          <h3 class="font-serif text-2xl font-semibold" style="color:${tc.textLight};">Complete ${c.nicheLabel} Project</h3>
        </div>
      </div>
      <div class="group relative overflow-hidden rounded-lg cursor-pointer" style="aspect-ratio:4/3;">
        <img src="${escHtml(projImg2)}" alt="Recent project" class="w-full h-full object-cover transition-transform duration-500 group-hover:scale-105" style="filter:brightness(0.6);">
        <div class="absolute inset-0 flex flex-col justify-end p-8">
          <p class="text-xs uppercase tracking-[0.15em] mb-2" style="color:${tc.accent};">${city} Metro Area</p>
          <h3 class="font-serif text-2xl font-semibold" style="color:${tc.textLight};">Premium Installation</h3>
        </div>
      </div>
    </div>
  </div>
</section>

<!-- SERVICES — editorial list format with niche icons (NOT card grid) -->
<section id="services" class="py-24 md:py-32 niche-pattern" style="background:${tc.bgAlt};">
  <div class="max-w-4xl mx-auto px-6 lg:px-10">
    <div class="mb-12 reveal">
      <p class="text-xs font-medium uppercase tracking-[0.2em] mb-3" style="color:${tc.accent};">Services</p>
      <h2 class="font-serif text-3xl md:text-4xl font-semibold" style="color:${tc.textLight};letter-spacing:-0.02em;">What We Do</h2>
    </div>
${serviceList}
  </div>
</section>

<!-- PULL-QUOTE TESTIMONIAL — single large quote -->
<section class="py-24 md:py-32">
  <div class="max-w-3xl mx-auto px-6 lg:px-10 text-center reveal">
    <div class="flex justify-center gap-1 mb-8">
      ${'<svg class="w-5 h-5" style="color:' + tc.accent + ';" fill="currentColor" viewBox="0 0 20 20"><path d="M9.049 2.927c.3-.921 1.603-.921 1.902 0l1.07 3.292a1 1 0 00.95.69h3.462c.969 0 1.371 1.24.588 1.81l-2.8 2.034a1 1 0 00-.364 1.118l1.07 3.292c.3.921-.755 1.688-1.54 1.118l-2.8-2.034a1 1 0 00-1.175 0l-2.8 2.034c-.784.57-1.838-.197-1.539-1.118l1.07-3.292a1 1 0 00-.364-1.118L2.98 8.72c-.783-.57-.38-1.81.588-1.81h3.461a1 1 0 00.951-.69l1.07-3.292z"/></svg>'.repeat(mainTestimonial.rating)}
    </div>
    <blockquote class="font-serif italic mb-8" style="color:${tc.textLight};font-size:clamp(1.3rem,2.5vw,1.8rem);line-height:1.4;">
      "${escHtml(mainTestimonial.text)}"
    </blockquote>
    <p class="text-sm font-medium uppercase tracking-[0.1em]" style="color:${tc.textMuted};">— ${escHtml(mainTestimonial.name)}</p>
  </div>
</section>

<!-- PROCESS — numbered steps -->
<section id="process" class="py-24 md:py-32 niche-pattern" style="background:${tc.bgAlt};">
  <div class="max-w-4xl mx-auto px-6 lg:px-10">
    <div class="text-center mb-16 reveal">
      <p class="text-xs font-medium uppercase tracking-[0.2em] mb-3" style="color:${tc.accent};">Our Process</p>
      <h2 class="font-serif text-3xl md:text-4xl font-semibold" style="color:${tc.textLight};letter-spacing:-0.02em;">How We Work</h2>
    </div>
    <div class="grid grid-cols-1 md:grid-cols-3 gap-12 reveal">
      <div>
        <span class="font-serif text-5xl font-semibold" style="color:${tc.accent};">01</span>
        <h3 class="font-serif text-xl font-semibold mt-4 mb-2" style="color:${tc.textLight};">Consultation</h3>
        <p class="text-sm leading-relaxed" style="color:${tc.textMuted};">We begin with a thorough assessment of your needs. Every project starts with listening — understanding your home, your goals, and your budget.</p>
      </div>
      <div>
        <span class="font-serif text-5xl font-semibold" style="color:${tc.accent};">02</span>
        <h3 class="font-serif text-xl font-semibold mt-4 mb-2" style="color:${tc.textLight};">Execution</h3>
        <p class="text-sm leading-relaxed" style="color:${tc.textMuted};">Our master technicians bring precision and care to every step. Premium materials, proper technique, and meticulous attention to detail throughout.</p>
      </div>
      <div>
        <span class="font-serif text-5xl font-semibold" style="color:${tc.accent};">03</span>
        <h3 class="font-serif text-xl font-semibold mt-4 mb-2" style="color:${tc.textLight};">Guarantee</h3>
        <p class="text-sm leading-relaxed" style="color:${tc.textMuted};">We stand behind every project with a comprehensive warranty. Your satisfaction isn't a goal — it's the only acceptable outcome.</p>
      </div>
    </div>
  </div>
</section>

<!-- CONSULTATION CTA -->
<section id="contact" class="py-24 md:py-32">
  <div class="max-w-xl mx-auto px-6 lg:px-10">
    <div class="text-center mb-10 reveal">
      <p class="text-xs font-medium uppercase tracking-[0.2em] mb-4" style="color:${tc.accent};">Get Started</p>
      <h2 class="font-serif text-3xl md:text-4xl font-semibold mb-3" style="color:${tc.textLight};letter-spacing:-0.02em;">Start a Conversation</h2>
      <p class="text-sm leading-relaxed mb-4" style="color:${tc.textMuted};">Tell us about your project. We'll schedule a consultation at your convenience.</p>
      <div class="flex flex-wrap items-center justify-center gap-3 text-[11px] uppercase tracking-[0.14em]" style="color:${tc.textMuted};">
        ${badges.slice(0, 3).map(b => `<span class="border px-3 py-1.5 rounded-full" style="border-color:${tc.border};">${escHtml(b)}</span>`).join('\n        ')}
        <a href="tel:${phoneHref}" class="transition-colors" style="color:${tc.accent};">Call ${phone}</a>
      </div>
    </div>
    <form id="contact-form" class="reveal" style="background:${tc.bgAlt};border:1px solid rgba(255,255,255,.05);border-radius:12px;padding:32px;">
      <div class="grid grid-cols-1 md:grid-cols-2 gap-4 mb-4">
        <div>
          <label class="block text-xs font-medium mb-1.5 uppercase tracking-wider" style="color:${tc.textMuted};">Name</label>
          <input type="text" name="name" required placeholder="John Smith" class="w-full px-4 py-3 rounded-lg text-sm outline-none transition-all" style="color:${tc.textLight};background:rgba(255,255,255,.04);border:1px solid rgba(255,255,255,.08);" onfocus="this.style.borderColor='${tc.accent}'" onblur="this.style.borderColor='rgba(255,255,255,.08)'">
        </div>
        <div>
          <label class="block text-xs font-medium mb-1.5 uppercase tracking-wider" style="color:${tc.textMuted};">Phone</label>
          <input type="tel" name="phone" required placeholder="(555) 123-4567" class="w-full px-4 py-3 rounded-lg text-sm outline-none transition-all" style="color:${tc.textLight};background:rgba(255,255,255,.04);border:1px solid rgba(255,255,255,.08);" onfocus="this.style.borderColor='${tc.accent}'" onblur="this.style.borderColor='rgba(255,255,255,.08)'">
        </div>
      </div>
      <div class="mb-4">
        <label class="block text-xs font-medium mb-1.5 uppercase tracking-wider" style="color:${tc.textMuted};">Service</label>
        <select name="service" required class="w-full px-4 py-3 rounded-lg text-sm outline-none transition-all" style="color:${tc.textLight};background:rgba(255,255,255,.04);border:1px solid rgba(255,255,255,.08);">
          <option value="" disabled selected style="color:#666;">Select a service...</option>
${serviceOpts}
        </select>
      </div>
      <div class="mb-5">
        <label class="block text-xs font-medium mb-1.5 uppercase tracking-wider" style="color:${tc.textMuted};">About Your Project</label>
        <textarea name="message" rows="3" placeholder="Tell us about the scope of work..." class="w-full px-4 py-3 rounded-lg text-sm outline-none resize-none transition-all" style="color:${tc.textLight};background:rgba(255,255,255,.04);border:1px solid rgba(255,255,255,.08);" onfocus="this.style.borderColor='${tc.accent}'" onblur="this.style.borderColor='rgba(255,255,255,.08)'"></textarea>
      </div>
      <button type="submit" class="w-full py-3.5 rounded-lg font-medium text-sm uppercase tracking-[0.08em] transition-all" style="background:${tc.accent};color:${tc.primary};" onmouseover="this.style.background='${tc.accentHover}'" onmouseout="this.style.background='${tc.accent}'">
        ${escHtml(c.cta1)}
      </button>
    </form>
  </div>
</section>

<!-- FOOTER — minimal -->
<footer class="py-12" style="border-top:1px solid rgba(255,255,255,.04);">
  <div class="max-w-6xl mx-auto px-6 lg:px-10">
    <div class="flex flex-col md:flex-row items-center justify-between gap-6">
      <div>
        <p class="font-serif text-lg font-semibold" style="color:${tc.textLight};">${biz}</p>
        <p class="text-xs mt-1" style="color:${tc.textMuted};">${c.nicheLabel} · ${escHtml(cityState)}</p>
      </div>
      <div class="flex items-center gap-6 text-xs" style="color:${tc.textMuted};">
        <a href="tel:${phoneHref}" class="transition-colors" style="color:${tc.textMuted};">${phone}</a>
        <span class="w-px h-3 bg-white/[.06]"></span>
        <span>Mon–Sat · 24/7 Emergency</span>
      </div>
    </div>
    <div class="mt-8 pt-6 text-center" style="border-top:1px solid rgba(255,255,255,.04);">
      <p class="text-xs" style="color:${tc.textMuted};">&copy; 2026 ${biz}. All rights reserved.</p>
    </div>
  </div>
</footer>

<!-- Toast -->
<div id="toast" class="fixed bottom-6 left-1/2 -translate-x-1/2 px-5 py-3 rounded-lg z-50 flex items-center gap-2 opacity-0 translate-y-4 transition-all duration-300 pointer-events-none" style="background:${tc.accent};color:${tc.primary};">
  <svg class="w-4 h-4" fill="currentColor" viewBox="0 0 20 20"><path fill-rule="evenodd" d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z" clip-rule="evenodd"/></svg>
  <span class="font-medium text-sm">We'll be in touch to schedule your consultation.</span>
</div>

<script>
(function(){
  // Nav: transparent → solid on scroll
  var nav=document.getElementById('navbar');
  window.addEventListener('scroll',function(){nav.classList.toggle('nav-solid',window.scrollY>80);});

  // Mobile menu
  var toggle=document.getElementById('mobile-toggle'),menu=document.getElementById('mobile-menu');
  toggle.addEventListener('click',function(){menu.classList.toggle('hidden');});
  document.querySelectorAll('.mobile-link').forEach(function(l){l.addEventListener('click',function(){menu.classList.add('hidden');});});

  // Smooth scroll
  document.querySelectorAll('a[href^="#"]').forEach(function(a){
    a.addEventListener('click',function(e){
      var t=document.querySelector(this.getAttribute('href'));
      if(t){e.preventDefault();window.scrollTo({top:t.offsetTop-80,behavior:'smooth'});}
    });
  });

  // Reveal
  var ro=new IntersectionObserver(function(entries){entries.forEach(function(e){if(e.isIntersecting){e.target.classList.add('active');ro.unobserve(e.target);}});},{threshold:0.1,rootMargin:'0px 0px -60px 0px'});
  document.querySelectorAll('.reveal').forEach(function(el){ro.observe(el);});

  // Form
  var form=document.getElementById('contact-form'),toast=document.getElementById('toast');
  form.addEventListener('submit',function(e){
    e.preventDefault();toast.style.opacity='1';toast.style.transform='translate(-50%,0)';toast.style.pointerEvents='auto';form.reset();
    setTimeout(function(){toast.style.opacity='0';toast.style.transform='translate(-50%,1rem)';toast.style.pointerEvents='none';},4000);
  });
})();
</script>

${widget}
</body>
</html>`;
  }
};
