/**
 * PREMIUM MODERN UTILITY family
 * Clean white bg, Space Grotesk + Inter, geometric card-grid system.
 * Think Stripe/Linear designed a home service website — clean, functional, premium.
 */
const { escHtml } = require('../shared/utils');
const { getCopy } = require('../shared/copy');
const { generateWidget } = require('../shared/widget');

module.exports = {
  name: 'modern',
  label: 'Premium Modern Utility',

  generate(lead, niche) {
    const c = getCopy('modern', niche, lead);
    const biz = escHtml(lead.business_name);
    const city = escHtml(lead.city || 'Your City');
    const state = escHtml(lead.state || '');
    const phone = escHtml(lead.phone || '(555) 000-0000');
    const cityState = [lead.city, lead.state].filter(Boolean).join(', ');

    const widget = generateWidget(lead, {
      emoji: c.emoji,
      headBg: '#4F46E5',
      avatarBg: '#4F46E5',
      fabBg: '#4F46E5',
      fabRadius: '50%',
      fabSize: '48px',
      panelRadius: '16px',
      bodyFont: "'Inter',sans-serif",
      headingFont: "'Space Grotesk',sans-serif",
      userMsgBg: '#4F46E5',
      sendBg: '#4F46E5',
      sendHoverBg: '#4338CA',
      linkColor: '#4F46E5',
      inputFocusBorder: '#4F46E5',
      inputFocusRing: 'rgba(79,70,229,.12)',
      qrBorder: 'rgba(79,70,229,.2)',
      qrColor: '#4F46E5',
      qrBg: 'rgba(79,70,229,.04)',
      qrHoverBg: '#4F46E5',
      qrRadius: '24px',
      inputRadius: '10px',
      msgBotRadius: '4px 14px 14px 14px',
      msgUserRadius: '14px 14px 4px 14px',
      chatBg: '#FAFBFC',
      fabShadow: '0 4px 16px rgba(79,70,229,.25)',
    }, c.quickReplies, c.serviceOptions);

    const serviceCards = c.services.map((svc, i) => `
          <div class="group bg-white border border-gray-200 rounded-xl p-6 hover:shadow-lg hover:border-indigo-200 transition-all duration-200 reveal">
            <div class="w-10 h-10 rounded-lg bg-indigo-50 flex items-center justify-center mb-4 group-hover:bg-indigo-100 transition-colors">
              <span class="text-indigo-600 font-bold text-lg">${i + 1}</span>
            </div>
            <h3 class="font-heading font-semibold text-gray-900 text-base mb-2">${escHtml(svc.title)}</h3>
            <p class="text-gray-500 text-sm leading-relaxed">${escHtml(svc.desc)}</p>
          </div>`).join('\n');

    const testimonialCards = c.testimonials.map(t => `
            <div class="flex-shrink-0 w-80 bg-white border border-gray-200 rounded-xl p-6 snap-start">
              <div class="flex gap-0.5 mb-3">${'<svg class="w-4 h-4 text-amber-400" fill="currentColor" viewBox="0 0 20 20"><path d="M9.049 2.927c.3-.921 1.603-.921 1.902 0l1.07 3.292a1 1 0 00.95.69h3.462c.969 0 1.371 1.24.588 1.81l-2.8 2.034a1 1 0 00-.364 1.118l1.07 3.292c.3.921-.755 1.688-1.54 1.118l-2.8-2.034a1 1 0 00-1.175 0l-2.8 2.034c-.784.57-1.838-.197-1.539-1.118l1.07-3.292a1 1 0 00-.364-1.118L2.98 8.72c-.783-.57-.38-1.81.588-1.81h3.461a1 1 0 00.951-.69l1.07-3.292z"/></svg>'.repeat(t.rating)}</div>
              <p class="text-gray-600 text-sm leading-relaxed mb-4">"${escHtml(t.text)}"</p>
              <p class="text-gray-900 text-sm font-semibold">${escHtml(t.name)}</p>
            </div>`).join('\n');

    const faqItems = c.faqs.map(faq => `
          <div class="faq-item border border-gray-200 rounded-xl overflow-hidden">
            <button class="faq-toggle w-full flex items-center justify-between p-5 text-left hover:bg-gray-50 transition-colors">
              <span class="font-heading font-semibold text-gray-900 text-sm pr-4">${escHtml(faq.q)}</span>
              <svg class="faq-icon w-5 h-5 text-gray-400 flex-shrink-0 transition-transform duration-200" fill="none" stroke="currentColor" stroke-width="2" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" d="M19 9l-7 7-7-7"/></svg>
            </button>
            <div class="faq-answer">
              <p class="px-5 pb-5 text-gray-500 text-sm leading-relaxed">${escHtml(faq.a)}</p>
            </div>
          </div>`).join('\n');

    const serviceOpts = c.serviceOptions.map(o => `              <option>${escHtml(o)}</option>`).join('\n');

    return `<!-- DEMO: ${biz} | Family: modern | Generated by Variation Engine -->
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta name="robots" content="noindex, nofollow">
<title>${biz} — ${c.nicheLabel} | ${escHtml(cityState)}</title>
<link rel="preconnect" href="https://fonts.googleapis.com">
<link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&family=Space+Grotesk:wght@400;500;600;700&display=swap" rel="stylesheet">
<script src="https://cdn.tailwindcss.com"></script>
<script>
tailwind.config={theme:{extend:{colors:{indigo:{50:'#EEF2FF',100:'#E0E7FF',200:'#C7D2FE',500:'#6366F1',600:'#4F46E5',700:'#4338CA',800:'#3730A3'}},fontFamily:{heading:['Space Grotesk','sans-serif'],body:['Inter','sans-serif']}}}}
</script>
<style>
body{font-family:'Inter',sans-serif;color:#111827;-webkit-font-smoothing:antialiased;}
h1,h2,h3,h4{font-family:'Space Grotesk',sans-serif;}
.faq-answer{max-height:0;overflow:hidden;transition:max-height .3s ease;}
.faq-answer.open{max-height:400px;}
.faq-icon.rotated{transform:rotate(180deg);}
.reveal{opacity:0;transform:translateY(12px);transition:opacity .4s ease,transform .4s ease;}
.reveal.active{opacity:1;transform:translateY(0);}
.scroll-container{scrollbar-width:none;-ms-overflow-style:none;}
.scroll-container::-webkit-scrollbar{display:none;}
</style>
</head>
<body class="bg-white font-body">

<!-- NAV -->
<nav id="navbar" class="sticky top-0 z-40 bg-white border-b border-gray-100 transition-shadow duration-200">
  <div class="max-w-6xl mx-auto px-4 sm:px-6 lg:px-8">
    <div class="flex items-center justify-between h-16">
      <a href="#" class="font-heading font-bold text-xl text-gray-900 tracking-tight">${biz}</a>
      <div class="hidden md:flex items-center gap-1">
        <a href="#services" class="px-4 py-2 text-sm text-gray-500 hover:text-gray-900 hover:bg-gray-50 rounded-full transition-all">Services</a>
        <a href="#reviews" class="px-4 py-2 text-sm text-gray-500 hover:text-gray-900 hover:bg-gray-50 rounded-full transition-all">Reviews</a>
        <a href="#how" class="px-4 py-2 text-sm text-gray-500 hover:text-gray-900 hover:bg-gray-50 rounded-full transition-all">How It Works</a>
        <a href="#contact" class="px-4 py-2 text-sm text-gray-500 hover:text-gray-900 hover:bg-gray-50 rounded-full transition-all">Contact</a>
      </div>
      <a href="#contact" class="hidden md:inline-flex items-center gap-2 bg-indigo-600 text-white text-sm font-semibold px-5 py-2.5 rounded-full hover:bg-indigo-700 transition-colors">
        ${escHtml(c.cta1)}
      </a>
      <button id="mobile-toggle" class="md:hidden p-2 text-gray-600" aria-label="Menu">
        <svg class="w-6 h-6" fill="none" stroke="currentColor" stroke-width="2" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" d="M4 6h16M4 12h16M4 18h16"/></svg>
      </button>
    </div>
  </div>
  <div id="mobile-menu" class="hidden md:hidden border-t border-gray-100 bg-white">
    <div class="px-4 py-4 space-y-2">
      <a href="#services" class="mobile-link block px-4 py-2.5 text-gray-700 hover:bg-gray-50 rounded-lg text-sm font-medium">Services</a>
      <a href="#reviews" class="mobile-link block px-4 py-2.5 text-gray-700 hover:bg-gray-50 rounded-lg text-sm font-medium">Reviews</a>
      <a href="#how" class="mobile-link block px-4 py-2.5 text-gray-700 hover:bg-gray-50 rounded-lg text-sm font-medium">How It Works</a>
      <a href="#contact" class="mobile-link block px-4 py-2.5 text-gray-700 hover:bg-gray-50 rounded-lg text-sm font-medium">Contact</a>
      <a href="#contact" class="block bg-indigo-600 text-white text-center text-sm font-semibold px-4 py-2.5 rounded-lg mt-2">${escHtml(c.cta1)}</a>
    </div>
  </div>
</nav>

<!-- HERO — minimal, no image -->
<section class="bg-white pt-20 pb-16 md:pt-28 md:pb-20">
  <div class="max-w-2xl mx-auto px-4 sm:px-6 lg:px-8 text-center">
    <div class="inline-flex items-center gap-2 px-3 py-1.5 bg-indigo-50 rounded-full mb-6">
      <span class="w-1.5 h-1.5 rounded-full bg-green-500"></span>
      <span class="text-xs font-medium text-indigo-700">Serving ${city} — Available Now</span>
    </div>
    <h1 class="font-heading font-bold text-gray-900 mb-5" style="font-size:clamp(2rem,4.5vw,3rem);line-height:1.1;letter-spacing:-0.03em;">
      ${escHtml(c.headline)}
    </h1>
    <p class="text-gray-500 text-lg leading-relaxed mb-8 max-w-lg mx-auto">${escHtml(c.subline)}</p>
    <div class="flex flex-col sm:flex-row gap-3 justify-center">
      <a href="#contact" class="inline-flex items-center justify-center gap-2 bg-indigo-600 text-white font-semibold px-7 py-3.5 rounded-full hover:bg-indigo-700 transition-colors text-sm">
        ${escHtml(c.cta1)}
        <svg class="w-4 h-4" fill="none" stroke="currentColor" stroke-width="2" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" d="M13 7l5 5m0 0l-5 5m5-5H6"/></svg>
      </a>
      <a href="#services" class="inline-flex items-center justify-center gap-2 border border-gray-200 text-gray-700 font-semibold px-7 py-3.5 rounded-full hover:bg-gray-50 transition-colors text-sm">
        ${escHtml(c.cta2)}
      </a>
    </div>
  </div>
</section>

<!-- STATS CARD -->
<section class="pb-16 md:pb-20">
  <div class="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8">
    <div class="bg-white border border-gray-200 rounded-2xl p-6 md:p-8 reveal">
      <div class="grid grid-cols-2 md:grid-cols-4 gap-6 md:gap-0 md:divide-x divide-gray-100">
        <div class="text-center md:px-6">
          <div class="font-heading font-bold text-2xl text-gray-900">${escHtml(c.stats.avgResponse)} min</div>
          <div class="text-xs text-gray-400 font-medium mt-1 uppercase tracking-wider">Avg Response</div>
        </div>
        <div class="text-center md:px-6">
          <div class="font-heading font-bold text-2xl text-gray-900">${escHtml(c.stats.jobs)}+</div>
          <div class="text-xs text-gray-400 font-medium mt-1 uppercase tracking-wider">Jobs Done</div>
        </div>
        <div class="text-center md:px-6">
          <div class="font-heading font-bold text-2xl text-gray-900">${escHtml(c.stats.rating)}★</div>
          <div class="text-xs text-gray-400 font-medium mt-1 uppercase tracking-wider">Google Rating</div>
        </div>
        <div class="text-center md:px-6">
          <div class="font-heading font-bold text-2xl text-gray-900">${escHtml(c.stats.years)} yr</div>
          <div class="text-xs text-gray-400 font-medium mt-1 uppercase tracking-wider">In Business</div>
        </div>
      </div>
    </div>
  </div>
</section>

<!-- SERVICES -->
<section id="services" class="bg-gray-50 py-16 md:py-20">
  <div class="max-w-6xl mx-auto px-4 sm:px-6 lg:px-8">
    <div class="text-center mb-12 reveal">
      <p class="text-indigo-600 text-xs font-bold uppercase tracking-widest mb-3">Our Services</p>
      <h2 class="font-heading font-bold text-gray-900 text-3xl md:text-4xl" style="letter-spacing:-0.025em;">Everything you need, one team.</h2>
    </div>
    <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
${serviceCards}
    </div>
  </div>
</section>

<!-- REVIEWS — horizontal scroll -->
<section id="reviews" class="py-16 md:py-20">
  <div class="max-w-6xl mx-auto px-4 sm:px-6 lg:px-8">
    <div class="flex items-end justify-between mb-8 reveal">
      <div>
        <p class="text-indigo-600 text-xs font-bold uppercase tracking-widest mb-3">Reviews</p>
        <h2 class="font-heading font-bold text-gray-900 text-2xl md:text-3xl" style="letter-spacing:-0.02em;">What our customers say</h2>
      </div>
      <div class="hidden md:flex items-center gap-1.5 text-sm text-gray-400">
        <span class="text-amber-400">★</span> ${escHtml(c.stats.rating)} on Google
      </div>
    </div>
    <div class="flex gap-5 overflow-x-auto snap-x snap-mandatory scroll-container pb-4 reveal">
${testimonialCards}
    </div>
  </div>
</section>

<!-- HOW IT WORKS — 3 steps -->
<section id="how" class="bg-gray-50 py-16 md:py-20">
  <div class="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">
    <div class="text-center mb-14 reveal">
      <p class="text-indigo-600 text-xs font-bold uppercase tracking-widest mb-3">How It Works</p>
      <h2 class="font-heading font-bold text-gray-900 text-2xl md:text-3xl" style="letter-spacing:-0.02em;">Simple as 1-2-3</h2>
    </div>
    <div class="grid grid-cols-1 md:grid-cols-3 gap-8 reveal">
      <div class="text-center">
        <div class="w-12 h-12 rounded-full bg-indigo-600 text-white font-heading font-bold text-lg flex items-center justify-center mx-auto mb-4">1</div>
        <h3 class="font-heading font-semibold text-gray-900 mb-2">Book</h3>
        <p class="text-gray-500 text-sm leading-relaxed">Request a quote online or give us a call. We'll confirm your appointment within minutes.</p>
      </div>
      <div class="text-center relative">
        <div class="hidden md:block absolute top-6 -left-4 w-8 border-t-2 border-dashed border-gray-300"></div>
        <div class="w-12 h-12 rounded-full bg-indigo-600 text-white font-heading font-bold text-lg flex items-center justify-center mx-auto mb-4">2</div>
        <h3 class="font-heading font-semibold text-gray-900 mb-2">Service</h3>
        <p class="text-gray-500 text-sm leading-relaxed">A licensed technician arrives on time, diagnoses the issue, and provides upfront pricing before work begins.</p>
      </div>
      <div class="text-center relative">
        <div class="hidden md:block absolute top-6 -left-4 w-8 border-t-2 border-dashed border-gray-300"></div>
        <div class="w-12 h-12 rounded-full bg-indigo-600 text-white font-heading font-bold text-lg flex items-center justify-center mx-auto mb-4">3</div>
        <h3 class="font-heading font-semibold text-gray-900 mb-2">Done</h3>
        <p class="text-gray-500 text-sm leading-relaxed">Job completed, site cleaned up, and backed by our satisfaction guarantee. It's that simple.</p>
      </div>
    </div>
  </div>
</section>

<!-- FAQ -->
<section id="faq" class="py-16 md:py-20">
  <div class="max-w-2xl mx-auto px-4 sm:px-6 lg:px-8">
    <div class="text-center mb-10 reveal">
      <p class="text-indigo-600 text-xs font-bold uppercase tracking-widest mb-3">FAQ</p>
      <h2 class="font-heading font-bold text-gray-900 text-2xl md:text-3xl" style="letter-spacing:-0.02em;">Common questions</h2>
    </div>
    <div class="space-y-3 reveal">
${faqItems}
    </div>
  </div>
</section>

<!-- CONTACT -->
<section id="contact" class="bg-gray-50 py-16 md:py-20">
  <div class="max-w-xl mx-auto px-4 sm:px-6 lg:px-8">
    <div class="text-center mb-8 reveal">
      <h2 class="font-heading font-bold text-gray-900 text-2xl md:text-3xl mb-2" style="letter-spacing:-0.02em;">${escHtml(c.cta1)}</h2>
      <p class="text-gray-500 text-sm">Fill out the form and we'll get back to you within 15 minutes.</p>
    </div>
    <form id="contact-form" class="bg-white border border-gray-200 rounded-2xl p-6 md:p-8 reveal">
      <div class="grid grid-cols-1 md:grid-cols-2 gap-4 mb-4">
        <div>
          <label class="block text-xs font-semibold text-gray-600 mb-1.5">Name</label>
          <input type="text" name="name" required placeholder="John Smith" class="w-full px-4 py-2.5 border border-gray-200 rounded-lg text-sm outline-none focus:border-indigo-500 focus:ring-2 focus:ring-indigo-100 transition-all">
        </div>
        <div>
          <label class="block text-xs font-semibold text-gray-600 mb-1.5">Phone</label>
          <input type="tel" name="phone" required placeholder="(555) 123-4567" class="w-full px-4 py-2.5 border border-gray-200 rounded-lg text-sm outline-none focus:border-indigo-500 focus:ring-2 focus:ring-indigo-100 transition-all">
        </div>
      </div>
      <div class="mb-4">
        <label class="block text-xs font-semibold text-gray-600 mb-1.5">Service</label>
        <select name="service" required class="w-full px-4 py-2.5 border border-gray-200 rounded-lg text-sm outline-none focus:border-indigo-500 focus:ring-2 focus:ring-indigo-100 transition-all text-gray-700">
          <option value="" disabled selected>Select a service...</option>
${serviceOpts}
        </select>
      </div>
      <div class="mb-5">
        <label class="block text-xs font-semibold text-gray-600 mb-1.5">Message (optional)</label>
        <textarea name="message" rows="3" placeholder="Describe your issue..." class="w-full px-4 py-2.5 border border-gray-200 rounded-lg text-sm outline-none focus:border-indigo-500 focus:ring-2 focus:ring-indigo-100 transition-all resize-none"></textarea>
      </div>
      <button type="submit" class="w-full bg-indigo-600 text-white font-heading font-semibold py-3 rounded-lg hover:bg-indigo-700 transition-colors text-sm">
        ${escHtml(c.cta1)}
      </button>
    </form>
  </div>
</section>

<!-- FOOTER -->
<footer class="bg-white border-t border-gray-100 py-12">
  <div class="max-w-6xl mx-auto px-4 sm:px-6 lg:px-8">
    <div class="grid grid-cols-1 md:grid-cols-3 gap-8">
      <div>
        <p class="font-heading font-bold text-gray-900 text-lg mb-2">${biz}</p>
        <p class="text-gray-400 text-sm">Fast, reliable ${c.nicheLabel.toLowerCase()} in ${escHtml(cityState)}.</p>
      </div>
      <div>
        <h4 class="text-xs font-bold text-gray-400 uppercase tracking-wider mb-3">Quick Links</h4>
        <ul class="space-y-2">
          <li><a href="#services" class="text-gray-500 hover:text-gray-900 text-sm transition-colors">Services</a></li>
          <li><a href="#reviews" class="text-gray-500 hover:text-gray-900 text-sm transition-colors">Reviews</a></li>
          <li><a href="#how" class="text-gray-500 hover:text-gray-900 text-sm transition-colors">How It Works</a></li>
          <li><a href="#contact" class="text-gray-500 hover:text-gray-900 text-sm transition-colors">Contact</a></li>
        </ul>
      </div>
      <div>
        <h4 class="text-xs font-bold text-gray-400 uppercase tracking-wider mb-3">Contact</h4>
        <p class="text-gray-500 text-sm mb-1">${phone}</p>
        <p class="text-gray-500 text-sm">Mon–Sat 7am–10pm · 24/7 Emergency</p>
      </div>
    </div>
    <div class="mt-10 pt-6 border-t border-gray-100 text-center">
      <p class="text-gray-300 text-xs">&copy; 2026 ${biz}. All rights reserved.</p>
    </div>
  </div>
</footer>

<!-- Toast -->
<div id="toast" class="fixed bottom-6 left-1/2 -translate-x-1/2 bg-gray-900 text-white px-5 py-3 rounded-lg z-50 flex items-center gap-2 shadow-lg opacity-0 translate-y-4 transition-all duration-300 pointer-events-none">
  <svg class="w-4 h-4 text-green-400" fill="currentColor" viewBox="0 0 20 20"><path fill-rule="evenodd" d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z" clip-rule="evenodd"/></svg>
  <span class="font-medium text-sm">Thanks! We'll be in touch within 15 minutes.</span>
</div>

<script>
(function(){
  // Navbar shadow on scroll
  var nav=document.getElementById('navbar');
  window.addEventListener('scroll',function(){nav.style.boxShadow=window.scrollY>20?'0 1px 3px rgba(0,0,0,.06)':'none';});

  // Mobile menu
  var toggle=document.getElementById('mobile-toggle'),menu=document.getElementById('mobile-menu');
  toggle.addEventListener('click',function(){menu.classList.toggle('hidden');});
  document.querySelectorAll('.mobile-link').forEach(function(l){l.addEventListener('click',function(){menu.classList.add('hidden');});});

  // Smooth scroll
  document.querySelectorAll('a[href^="#"]').forEach(function(a){
    a.addEventListener('click',function(e){
      var t=document.querySelector(this.getAttribute('href'));
      if(t){e.preventDefault();window.scrollTo({top:t.offsetTop-72,behavior:'smooth'});}
    });
  });

  // Reveal on scroll
  var ro=new IntersectionObserver(function(entries){entries.forEach(function(e){if(e.isIntersecting){e.target.classList.add('active');ro.unobserve(e.target);}});},{threshold:0.1,rootMargin:'0px 0px -40px 0px'});
  document.querySelectorAll('.reveal').forEach(function(el){ro.observe(el);});

  // FAQ
  document.querySelectorAll('.faq-toggle').forEach(function(btn){
    btn.addEventListener('click',function(){
      var ans=this.nextElementSibling,icon=this.querySelector('.faq-icon'),open=ans.classList.contains('open');
      document.querySelectorAll('.faq-answer').forEach(function(a){a.classList.remove('open');});
      document.querySelectorAll('.faq-icon').forEach(function(i){i.classList.remove('rotated');});
      if(!open){ans.classList.add('open');icon.classList.add('rotated');}
    });
  });

  // Form
  var form=document.getElementById('contact-form'),toast=document.getElementById('toast');
  form.addEventListener('submit',function(e){
    e.preventDefault();toast.style.opacity='1';toast.style.transform='translate(-50%,0)';toast.style.pointerEvents='auto';form.reset();
    setTimeout(function(){toast.style.opacity='0';toast.style.transform='translate(-50%,1rem)';toast.style.pointerEvents='none';},4000);
  });
})();
</script>

${widget}
</body>
</html>`;
  }
};
